name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: Check if directory is writable
            run: |
              mkdir -p ${{ env.APPDATA }}/ASP.NET/https
              echo "Test" > ${{ env.APPDATA }}/ASP.NET/https/testfile.txt
              ls -la ${{ env.APPDATA }}/ASP.NET/https
